version: 2.1
orbs: 
  node: circleci/node@5.0.1
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
workflows:
  test:
    jobs:
      - node/test:
          test-results-for: jest
