name: Lint

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ andres ]
  pull_request:
    branches: [ andres ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  eslint:
    build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2   
    - name: Run ESLint
      run: eslint . --ext .js,.jsx

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.