name: Lint

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ andres ]
  pull_request:
    branches: [ andres ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.